# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

language: julia

os: windows

julia:
  - 1.2

script:
  # ver: Windows Server 1803
  - cmd.exe /C 'chcp 949'

  # echo cp -r c:\\\\\\\\julia c:\\\\\\\\테스트 | iconv -f utf-8 -t cp949 > cp_949.sh
  - iconv -f cp949 -t utf-8 cp_949.sh
  - ./cp_949.sh

  # echo ls c:\\\\\\\\테스트 | iconv -f utf-8 -t cp949 > ls_949.sh
  - iconv -f cp949 -t utf-8 ls_949.sh
  - ./ls_949.sh

  # echo c:\\\\\\\\테스트\\\\\\\\bin\\\\\\\\julia.exe -E "1" | iconv -f utf-8 -t cp949 > jl_949.sh
  - iconv -f cp949 -t utf-8 jl_949.sh
  - ./jl_949.sh

  # echo cmd.exe /C 'c:\\\\테스트\\\\bin\\\\julia.exe -E "1"' | iconv -f utf-8 -t cp949 > cmd_949.sh
  - iconv -f cp949 -t utf-8 cmd_949.sh
  - ./cmd_949.sh
